baseURL: /
languageCode: en-us
title: Hugo Fresh Theme
theme: hugo-fresh
publishDir: ../../src/main/resources/static

params:
  font:
    name: 'Open Sans'
    sizes: [400, 600]
  hero:
    # Main hero title
    title: Up and running.
    # Hero subtitle (optional)
    # subtitle: Lorem ipsum sit dolor amet is dummy text used by the typography industry
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: '#'
    # Hero image (from /images/___)
    image: illustrations/worker.svg

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    - title: Home
      url: /
    - title: Dropdown
      sublinks:
        - title: Dropdown item
          url: /
        - title: Dropdown item
          url: /
        - title: Dropdown item
          url: /
    - title: Log in
      url: /
      button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
      - title: User
        icon: user
        links:
          - text: Profile
            url: /
          - text: Account
            url: /
          - text: Settings
            url: /
      - title: Messages
        icon: envelope
        links:
          - text: Inbox
            url: /
          - text: Compose
            url: /
      - title: Images
        icon: image
        links:
          - text: Library
            url: /
          - text: Upload
            url: /
      - title: Settings
        icon: cog
        links:
          - text: User settings
            url: /
          - text: App settings
            url: /
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      - link: https://github.com/olsio/
        # Icons are from Font Awesome
        icon: github
      - link: https://twitter.com/inbx
        icon: twitter
    bulmalogo: false
    product:
      - text: Discover features
        link: /
      - text: Why choose our product?
        link: /
      - text: Compare features
        link: /
      - text: Our roadmap
        link: /
      - text: Request features
        link: /
    docs:
      - text: Get started
        link: /
      - text: User guides
        link: /
      - text: Admin guide
        link: /
      - text: Developers
        link: /
